{% set version = "2.7.1" %}
{% set sha256 = "10a78d3007413a6d4c983d2acbf03ef84b622b82bd9a59c6bd9fbdde9d0298ca" %}
{% set CONDA_BOOST ="1.64" %}
{% set CONDA_ZLIB ="1.2.8" %}
{% set CONDA_BZIP2 ="1.0" %}

package:
  name: sparcle
  version: {{ version }}

source:
    url: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-src.tar.gz
    fn: ncbi-blast-{{ version }}+-src.tar.gz
    sha256: {{ sha256 }}
    patches:
      - boost_106400.patch
      - rpsb.0.0.1.patch

build:
  number: 1
  string: boost{{ CONDA_BOOST }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - gcc  # [linux]
    - boost {{ CONDA_BOOST }}*
    - zlib {{ CONDA_ZLIB }}*
    - bzip2 {{ CONDA_BZIP2 }}*
    - gnutls
    - nettle 3.3|3.3.*
    - pcre
    - time
  run:
    - libgcc  # [linux]
    - boost {{ CONDA_BOOST }}*
    - zlib {{ CONDA_ZLIB }}*
    - bzip2 {{ CONDA_BZIP2 }}*
    - gnutls
    - nettle 3.3|3.3.*
    - blast 2.7.1
    - pcre
    - perl
    - perl-list-moreutils
    - perl-archive-tar
test:
  commands:
    - echo "rpsbproc"
about:
  home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
  license: Public Domain
  summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.
